---
google_D1:
  hostname: 10.225.252.8
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb1

google_D2:
  hostname: 10.225.252.2
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup 
    tb: tb1

google_D3: 
  hostname: 10.225.252.3
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb1

google_D5:
  hostname: 10.225.252.4
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb1

google_D7:
  hostname: 10.225.252.9
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb1

google_D8: 
  hostname: 10.225.252.10
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb1

google_D9:
  hostname: 10.225.252.6
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb1

D10_TB1_5508_CX:  	 
  hostname: 10.225.252.132
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb1

D11_TB1_5508_PF:  	 
  hostname: 10.225.252.133
  port: 22
  groups:
    - ios_xr
  data:  
    role: pf
    tb: tb1

D12_TB1_5011_ECSR:
  hostname: 10.225.252.229
  port: 22
  groups:
    - ios_xr
  data:  
    role: ecsr
    tb: tb1

D13_TB1_55A1_sCX: 	
  hostname: 10.225.252.239
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb1

google_D1_tb2:
  hostname: 10.225.252.54
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb2

google_D2_tb2:
  hostname: 10.225.252.56
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb2

google_D3_tb2:
  hostname: 10.225.252.57
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb2

google_D5_tb2:
  hostname: 10.225.252.58
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb2

google_D7_tb2:
  hostname: 10.225.252.49
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb2

google_D8_tb2: 
  hostname: 10.225.252.50
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb2

google_D9_tb2:
  hostname: 10.225.252.55
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb2

D10_TB2_5508_CX:  	 
  hostname: 10.225.252.137
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb2

D11_TB2_5508_PF:  	 
  hostname: 10.225.252.136
  port: 22
  groups:
    - ios_xr
  data:  
    role: pf
    tb: tb2

D12_TB2_5011_ECSR:
  hostname: 10.225.252.222
  port: 22
  groups:
    - ios_xr
  data:  
    role: ecsr
    tb: tb2

D16_TB2_55A1_sCX:  	 
  hostname: 10.225.252.138
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb2

google_D1_tb3:
  hostname: 10.225.252.99
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb3

google_D2_tb3:
  hostname: 10.225.252.101
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb3

google_D3_tb3:
  hostname: 10.225.252.102
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb3

google_D5_tb3:
  hostname: 10.225.252.103
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb3

google_D7_tb3:
  hostname: 10.225.252.94
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb3

google_D8_tb3:
  hostname: 10.225.252.95
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb3

google_D9_tb3:
  hostname: 10.225.252.100
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb3

D10_TB3_5508_CX: 	  	 
  hostname: 10.225.252.104
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb3

D11_TB3_5508_PF:
  hostname: 10.225.252.96
  port: 22
  groups:
    - ios_xr
  data:  
    role: pf
    tb: tb3

D12_TB3_5011_ECSR:   	 
  hostname: 10.225.252.91
  port: 22
  groups:
    - ios_xr
  data:  
    role: ecsr
    tb: tb3

D14_TB3_5508_BX:
  hostname: 10.225.252.141
  port: 22
  groups:
    - ios_xr
  data:  
    role: bx
    tb: tb3

google_D1_tb4:
  hostname: 10.225.252.235
  port: 22
  groups:
    - ios_xr
  data:  
    role: bd
    tb: tb4

google_D2_tb4: 	  	 
  hostname: 10.225.252.238
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb4

google_D3_tb4:  	 
  hostname: 10.225.252.237
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb4

google_D5_tb4:  	 
  hostname: 10.225.252.233
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb4

google_D7_tb4:  	 
  hostname: 10.225.252.228
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb4

google_D8_tb4:  	 
  hostname: 10.225.252.227
  port: 22
  groups:
    - ios_xr
  data:  
    role: bdbx_sup
    tb: tb4

google_D9_tb4:
  hostname: 10.225.252.232
  port: 22
  groups:
    - ios_xr
  data:  
    role: bx
    tb: tb4

D10_TB4_5508_CX: 	 
  hostname: 10.225.252.226
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb4

D11_TB4_5508_PF:	 
  hostname: 10.225.252.236
  port: 22
  groups:
    - ios_xr
  data:  
    role: pf
    tb: tb4

D12_TB4_5011_ECSR:
  hostname: 10.225.252.221
  port: 22
  groups:
    - ios_xr
  data:  
    role: ecsr
    tb: tb4

D10_TB6_5508_CX: 	  	 
  hostname: 10.225.252.135
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb6

D11_TB6_5508_PF:  	 
  hostname: 10.225.252.134
  port: 22
  groups:
    - ios_xr
  data:  
    role: pf
    tb: tb6

D12_TB6_5011_ECSR:  	 
  hostname: 10.225.252.140
  port: 22
  groups:
    - ios_xr
  data:  
    role: ecsr
    tb: tb6

D13_TB6_55A1_sCX:  	 
  hostname: 10.225.252.150
  port: 22
  groups:
    - ios_xr
  data:  
    role: cx
    tb: tb6

D14_TB6_5501_sPF:	 
  hostname: 10.225.252.151
  port: 22
  groups:
    - ios_xr
  data:  
    role: pf
    tb: tb6

D15_TB6_5011_ECSR:
  hostname: 10.225.252.139
  port: 22
  groups:
    - ios_xr
  data:  
    role: ecsr
    tb: tb6

# D16_TB6_55A1_sPF:  
#   hostname: 10.225.252.138
#   port: 22
#   groups:
#     - ios_xr
#   data:  
#     role: pf
#     tb: tb6

